### ISSUE TITLE
An exception has been thrown during the rendering of a template ("array_merge(): Argument #2 is not an array").

### ISSUE THREAD

**Issue by paulcosmos** [paulmassen/grav-plugin-seo#78]
I've used this plugin in the past (it's fantastic) but when using it with a site I'm currently developing, I get the following error when trying to access pages using a particular template (other pages so far are not affected):

> An exception has been thrown during the rendering of a template ("array_merge(): Argument #2 is not an array").

Example of error:
<img width="1182" alt="Screenshot 2019-08-12 at 12 50 06" src="https://user-images.githubusercontent.com/24660807/62864311-44e63580-bd03-11e9-8c4b-ed467104ccdc.png">

The metadata template is included in the head of the page template as per the instructions.
These pages are using a blueprint that extends the default yaml file, all I'm doing is using `replace@` to insert my own fields into the first tab (the default 'Content' tab). 

My yaml file content included below for reference (is there an issue with this perhaps?):

```
title: Facility
@extends:
    type: default
    context: blueprints://pages
form:
  fields:
    tabs:
      type: tabs
      active: 1

      # Replace the first tab in the admin page
      fields:
        content:
          replace@: true          
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:

            header.facility_title:
              type: text
              autofocus: true
              style: vertical
              label: Facility Title
            
            header.facility_summary:
              type: text
              style: vertical
              label: Summary (used for page snippets)

            header.facility_description:
              type: markdown
              style: vertical
              label: Facility Description

            header.facility_images:
              type: PageMedia
              label: Add images
```
